/** 管理画面で扱う求人1件の型（jobs テーブルの列に対応）。 */
export type AdminJob = {
  id: number | string;
  field_id: string;
  status: "draft" | "published";
  is_new: boolean;
  region: string;
  title_ja: string;
  title_zh: string;
  area_ja: string;
  area_zh: string;
  salary_min: number;
  salary_max: number;
  annual_min: number | null;
  annual_max: number | null;
  tags: string[];
  benefits: string[];
  chinese_support: boolean;
  hours_ja: string | null;
  hours_zh: string | null;
  holidays_ja: string | null;
  holidays_zh: string | null;
  overtime_ja: string | null;
  overtime_zh: string | null;
  housing_ja: string | null;
  housing_zh: string | null;
  requirements_ja: string | null;
  requirements_zh: string | null;
  bonus_ja: string | null;
  bonus_zh: string | null;
  company_ja: string | null;
  company_zh: string | null;
  chinese_staff_ja: string | null;
  chinese_staff_zh: string | null;
  desc_ja: string | null;
  desc_zh: string | null;
  duties_ja: string[];
  duties_zh: string[];
  company_id: number | null;
  /** 一覧クエリの埋め込み（select("*, companies(id, name)")）で入る。単体取得時は無い。 */
  companies?: { id: number | string; name: string | null } | null;
  created_at?: string | null;
  updated_at?: string | null;
};
