-- ==========================================================
-- 樱聘 YingPin β版 データベース初期セットアップ（1ファイル版）
-- このファイルの内容をすべてコピーし、Supabaseの SQL Editor に
-- 貼り付けて「Run」を押してください。何度実行しても安全です。
-- 自動生成: 0001_schema.sql + 0002_seed.sql の結合（編集は各migrationsで）
-- ==========================================================

-- =========================================================
-- 樱聘 YingPin β版 データベーススキーマ（T-02）
-- テーブル定義＋RLS（行レベルセキュリティ）
-- Supabase の SQL Editor に貼り付けて実行する。
-- 冪等（何度実行しても安全）になるよう IF NOT EXISTS / OR REPLACE を使用。
-- =========================================================

-- ---------- 列挙型 ----------
do $$ begin
  create type gender_type as enum ('male', 'female', 'other');
exception when duplicate_object then null; end $$;

do $$ begin
  create type residence_type as enum ('jp', 'cn');
exception when duplicate_object then null; end $$;

do $$ begin
  create type job_status as enum ('draft', 'published', 'closed');
exception when duplicate_object then null; end $$;

do $$ begin
  -- 応募ステータス: 新規→連絡済→面接→内定→入社／辞退
  create type application_status as enum ('new', 'contacted', 'interview', 'offer', 'hired', 'declined');
exception when duplicate_object then null; end $$;

-- ---------- 更新時刻の自動更新 ----------
create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

-- ---------- staff_users（スタッフ／管理者） ----------
-- このテーブルに行がある auth ユーザーだけが管理画面にアクセスできる。
create table if not exists staff_users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  name text,
  created_at timestamptz not null default now()
);

-- スタッフ判定ヘルパー（RLSポリシーから参照）。
create or replace function is_staff()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from staff_users where id = auth.uid());
$$;

-- ---------- fields（特定技能2号移行対象の11分野・参照マスタ） ----------
create table if not exists fields (
  id text primary key,          -- 'restaurant' など（モックのFIELDS.idと一致）
  emoji text not null,
  color text not null,
  name_ja text not null,
  name_zh text not null,
  sort_order int not null default 0
);

-- ---------- members（会員／求職者） ----------
-- id = auth.users.id（本人だけが自分の行を読み書きできる）。
create table if not exists members (
  id uuid primary key references auth.users(id) on delete cascade,
  member_no text unique,             -- 表示用の会員番号 YP-YYYYMMDD-XXXX
  last_name text not null,
  first_name text not null,
  pinyin text not null,
  birth date,
  gender gender_type,
  nationality text not null default 'cn',
  residence residence_type not null default 'jp',
  address text,
  phone_code text not null default '+81',
  phone text not null,
  wechat_id text not null,
  email text,
  jlpt text,                         -- 'N1'〜'N5' / 'none'
  ssw_fields text[] not null default '{}',  -- 合格済み特定技能分野（fields.idの配列）
  other_qual text,
  verified boolean not null default false,  -- スタッフがWeChat本人確認後にON
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
drop trigger if exists trg_members_updated on members;
create trigger trg_members_updated before update on members
  for each row execute function set_updated_at();

-- ---------- jobs（求人。企業が特定されない情報のみ） ----------
create table if not exists jobs (
  id bigint generated by default as identity primary key,
  field_id text not null references fields(id),
  status job_status not null default 'draft',
  is_new boolean not null default false,
  region text not null,              -- 'kanto' など
  title_ja text not null, title_zh text not null,
  area_ja text not null,  area_zh text not null,
  salary_min int not null, salary_max int not null,   -- 月給（万円）
  annual_min int, annual_max int,                     -- 想定年収（万円）
  tags text[] not null default '{}',
  benefits text[] not null default '{}',
  chinese_support boolean not null default false,
  hours_ja text, hours_zh text,
  holidays_ja text, holidays_zh text,
  overtime_ja text, overtime_zh text,
  housing_ja text, housing_zh text,
  requirements_ja text, requirements_zh text,
  bonus_ja text, bonus_zh text,
  company_ja text, company_zh text,          -- 匿名の企業プロフィール（業種・規模のみ）
  chinese_staff_ja text, chinese_staff_zh text,
  desc_ja text, desc_zh text,
  duties_ja text[] not null default '{}',
  duties_zh text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
drop trigger if exists trg_jobs_updated on jobs;
create trigger trg_jobs_updated before update on jobs
  for each row execute function set_updated_at();
create index if not exists idx_jobs_status on jobs(status);
create index if not exists idx_jobs_field on jobs(field_id);
create index if not exists idx_jobs_region on jobs(region);

-- ---------- applications（応募） ----------
create table if not exists applications (
  id bigint generated by default as identity primary key,
  member_id uuid not null references members(id) on delete cascade,
  job_id bigint not null references jobs(id) on delete cascade,
  status application_status not null default 'new',
  staff_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (member_id, job_id)         -- 同じ求人への重複応募を防ぐ
);
drop trigger if exists trg_applications_updated on applications;
create trigger trg_applications_updated before update on applications
  for each row execute function set_updated_at();
create index if not exists idx_applications_member on applications(member_id);
create index if not exists idx_applications_job on applications(job_id);
create index if not exists idx_applications_status on applications(status);

-- ---------- favorites（お気に入り） ----------
create table if not exists favorites (
  member_id uuid not null references members(id) on delete cascade,
  job_id bigint not null references jobs(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (member_id, job_id)
);

-- =========================================================
-- RLS（行レベルセキュリティ）: 全テーブルで有効化
-- 原則: 会員は自分のデータのみ／求人閲覧はログイン必須／管理操作はスタッフのみ
-- =========================================================
alter table staff_users enable row level security;
alter table fields      enable row level security;
alter table members     enable row level security;
alter table jobs        enable row level security;
alter table applications enable row level security;
alter table favorites   enable row level security;

-- fields: 誰でも閲覧可（分野名は機密でない）。編集はスタッフのみ。
drop policy if exists fields_read on fields;
create policy fields_read on fields for select using (true);
drop policy if exists fields_staff_write on fields;
create policy fields_staff_write on fields for all using (is_staff()) with check (is_staff());

-- staff_users: スタッフ本人のみ自分の行を閲覧可（管理はダッシュボード/SQLで行う）。
drop policy if exists staff_self_read on staff_users;
create policy staff_self_read on staff_users for select using (id = auth.uid());

-- members: 本人は自分の行をCRUD。スタッフは全会員を閲覧・更新（本人確認フラグ等）。
drop policy if exists members_self_read on members;
create policy members_self_read on members for select using (id = auth.uid() or is_staff());
drop policy if exists members_self_insert on members;
create policy members_self_insert on members for insert with check (id = auth.uid());
drop policy if exists members_self_update on members;
create policy members_self_update on members for update
  using (id = auth.uid() or is_staff()) with check (id = auth.uid() or is_staff());

-- jobs: ログイン済みユーザーは公開中の求人のみ閲覧可。スタッフは全操作可。
drop policy if exists jobs_read_published on jobs;
create policy jobs_read_published on jobs for select
  using ((status = 'published' and auth.uid() is not null) or is_staff());
drop policy if exists jobs_staff_write on jobs;
create policy jobs_staff_write on jobs for all using (is_staff()) with check (is_staff());

-- applications: 本人は自分の応募をCRUD。スタッフは全応募を閲覧・更新。
drop policy if exists apps_self_read on applications;
create policy apps_self_read on applications for select using (member_id = auth.uid() or is_staff());
drop policy if exists apps_self_insert on applications;
create policy apps_self_insert on applications for insert with check (member_id = auth.uid());
drop policy if exists apps_staff_update on applications;
create policy apps_staff_update on applications for update using (is_staff()) with check (is_staff());

-- favorites: 本人のみ自分のお気に入りをCRUD。
drop policy if exists favs_self_all on favorites;
create policy favs_self_all on favorites for all
  using (member_id = auth.uid()) with check (member_id = auth.uid());

-- =========================================================
-- スタッフの登録方法（初回のみ・手動）
-- 1) 管理者本人がサイトから電話番号＋パスワードで会員登録またはログイン
-- 2) Supabase の Authentication → Users で自分の User UID をコピー
-- 3) 下のコメントを外し、UIDを貼って実行:
-- insert into staff_users (id, email, name)
--   values ('ここにUID', 'staff@example.com', '担当者名')
--   on conflict (id) do nothing;
-- =========================================================


-- =========================================================
-- 樱聘 YingPin シードデータ（T-02・自動生成）
-- 生成元: assets/js/data.js ／ 生成: app/supabase/_generate_seed.js
-- 特定技能2号移行対象の11分野＋サンプル求人14件（すべてダミー）。
-- 既存データを消してから入れ直すため、何度でも安全に再実行できる。
-- =========================================================

-- 分野マスタ（存在すれば更新）
insert into fields (id, emoji, color, name_ja, name_zh, sort_order) values
  ('building', '🧹', '#38BDF8', 'ビルクリーニング', '楼宇清洁', 0),
  ('manufacturing', '🏭', '#6366F1', '工業製品製造業', '工业产品制造业', 1),
  ('construction', '🏗️', '#F59E0B', '建設', '建筑', 2),
  ('shipbuilding', '🚢', '#0EA5E9', '造船・舶用工業', '造船·船舶工业', 3),
  ('automobile', '🔧', '#8B5CF6', '自動車整備', '汽车维修', 4),
  ('aviation', '✈️', '#06B6D4', '航空', '航空', 5),
  ('accommodation', '🏨', '#EC4899', '宿泊', '酒店住宿', 6),
  ('agriculture', '🌾', '#22C55E', '農業', '农业', 7),
  ('fishery', '🐟', '#3B82F6', '漁業', '渔业', 8),
  ('food_mfg', '🍱', '#F97316', '飲食料品製造業', '食品饮料制造', 9),
  ('restaurant', '🍜', '#EF4444', '外食業', '餐饮业', 10)
on conflict (id) do update set
  emoji = excluded.emoji, color = excluded.color,
  name_ja = excluded.name_ja, name_zh = excluded.name_zh, sort_order = excluded.sort_order;

-- サンプル求人（id一致なら上書き＝再実行しても応募データを消さない）
insert into jobs (
  id, field_id, status, is_new, region, title_ja, title_zh, area_ja, area_zh, salary_min, salary_max, annual_min, annual_max, tags, benefits, chinese_support, hours_ja, hours_zh, holidays_ja, holidays_zh, overtime_ja, overtime_zh, housing_ja, housing_zh, requirements_ja, requirements_zh, bonus_ja, bonus_zh, company_ja, company_zh, chinese_staff_ja, chinese_staff_zh, desc_ja, desc_zh, duties_ja, duties_zh
) values
  (1, 'restaurant', 'published', true, 'kanto',
   'ラーメンチェーンのキッチンスタッフ', '拉面连锁店 后厨员工', '東京都 新宿区', '东京都 新宿区',
   21, 25, 300, 360,
   ARRAY['dorm', 'chinese', 'noExp']::text[], ARRAY['social', 'meal', 'jpLesson', 'bonus', 'dorm', 'support2']::text[], true,
   'シフト制・実働8時間（10:00〜23:00の間）', '排班制·实际工作8小时（10:00〜23:00之间）', '週休2日制・年間休日110日', '每周休2天·全年休110天', '月平均10時間程度', '月均约10小时',
   '借上げ社宅あり（家賃の50%を会社負担）', '公司租赁宿舍（房租公司承担50%）', '特定技能1号（外食業）／日本語N4以上', '特定技能1号（餐饮业）／日语N4以上', '賞与年2回（計2ヶ月分）・昇給年1回', '奖金每年2次（共2个月工资）·每年加薪1次',
   '全国200店舗以上を展開する外食チェーン（従業員約1,200名）', '全国拥有200多家门店的连锁餐饮企业（员工约1,200人）', '中国人スタッフ15名在籍', '已有15名中国员工',
   '人気ラーメンチェーンの店舗キッチンで、仕込み・調理・盛り付けを担当します。マニュアルと研修が充実しており、日本での飲食経験がなくても安心してスタートできます。', '在人气拉面连锁店的后厨，负责备料、烹饪和摆盘。操作手册和培训体系完善，即使没有在日本餐饮业的经验也能安心上手。', ARRAY['仕込み・調理・盛り付け', '食材の発注・在庫管理の補助', 'キッチンの衛生管理']::text[], ARRAY['备料·烹饪·摆盘', '协助食材订购·库存管理', '后厨卫生管理']::text[]),
  (2, 'restaurant', 'published', false, 'kansai',
   '中華レストランのホール・キッチンスタッフ', '中餐厅 前厅·后厨员工', '大阪府 大阪市（難波）', '大阪府 大阪市（难波）',
   20, 24, 280, 340,
   ARRAY['dorm', 'chinese']::text[], ARRAY['social', 'meal', 'bonus', 'dorm']::text[], true,
   'シフト制・実働8時間（11:00〜23:00の間）', '排班制·实际工作8小时（11:00〜23:00之间）', '週休2日制（シフト）・年間休日105日', '每周休2天（排班制）·全年休105天', '月平均15時間程度', '月均约15小时',
   '寮あり（個室・家賃2万円）', '有宿舍（单人间·月租2万日元）', '特定技能1号（外食業）／日本語N4以上（ホールはN3歓迎）', '特定技能1号（餐饮业）／日语N4以上（前厅欢迎N3）', '賞与年1回・昇給あり', '奖金每年1次·有加薪',
   '関西で30店舗を展開する中華料理チェーン（従業員約400名）', '在关西拥有30家门店的中餐连锁企业（员工约400人）', '中国人スタッフ28名在籍・店長登用実績あり', '已有28名中国员工·有晋升店长的先例',
   '本格中華レストランでホールまたはキッチンを担当します。中国語がそのまま活かせる職場で、同郷の仲間も多く、日本が初めてでも働きやすい環境です。', '在正宗中餐厅担任前厅或后厨工作。可以直接发挥中文优势，同乡同事多，即使初到日本也能轻松适应。', ARRAY['ホール接客・オーダー対応', '調理・調理補助', '開店・閉店作業']::text[], ARRAY['前厅接待·点单服务', '烹饪·烹饪辅助', '开店·闭店作业']::text[]),
  (3, 'food_mfg', 'published', false, 'kanto',
   'お弁当・お惣菜工場の製造スタッフ', '便当·熟食工厂 生产员工', '埼玉県 川越市', '埼玉县 川越市',
   19, 23, 260, 320,
   ARRAY['dorm', 'noExp', 'lowOT', 'chinese']::text[], ARRAY['social', 'meal', 'dorm', 'jpLesson', 'bonus']::text[], true,
   '2交替制（6:00〜15:00／13:00〜22:00）', '两班倒（6:00〜15:00／13:00〜22:00）', '週休2日（工場カレンダー）・年間休日115日', '每周休2天（按工厂日历）·全年休115天', '月平均10時間程度', '月均约10小时',
   '寮あり（家具家電付き・家賃1.5万円）', '有宿舍（带家具家电·月租1.5万日元）', '特定技能1号（飲食料品製造業）／日本語N5以上', '特定技能1号（食品饮料制造）／日语N5以上', '賞与年2回・昇給年1回', '奖金每年2次·每年加薪1次',
   'コンビニ向け食品を製造する大手食品メーカーグループ（従業員約800名）', '为便利店生产食品的大型食品集团（员工约800人）', '中国人スタッフ35名在籍', '已有35名中国员工',
   '有名コンビニのお弁当・お惣菜を作る清潔な工場でのお仕事です。ライン作業が中心で、日本語がまだ少なくても始めやすく、先輩の中国人スタッフも多数活躍しています。', '在为知名便利店生产便当和熟食的洁净工厂工作。以流水线作业为主，日语基础不多也容易上手，有很多中国前辈员工。', ARRAY['食材の計量・盛り付け', '製造ラインでの調理補助', '検品・梱包']::text[], ARRAY['食材称量·摆盘', '流水线烹饪辅助', '检验·包装']::text[]),
  (4, 'food_mfg', 'published', true, 'hokkaido_tohoku',
   '乳製品工場の製造オペレーター', '乳制品工厂 生产操作员', '北海道 帯広市', '北海道 带广市',
   18, 22, 250, 310,
   ARRAY['dorm', 'lowOT', 'noExp']::text[], ARRAY['social', 'dorm', 'flight', 'bonus']::text[], false,
   '日勤中心（8:00〜17:00）', '以白班为主（8:00〜17:00）', '週休2日・年間休日120日', '每周休2天·全年休120天', '月平均5時間程度', '月均约5小时',
   '寮あり（家賃1万円・水道光熱費込み）', '有宿舍（月租1万日元·含水电费）', '特定技能1号（飲食料品製造業）／日本語N5以上', '特定技能1号（食品饮料制造）／日语N5以上', '賞与年2回', '奖金每年2次',
   '北海道の乳製品メーカー（従業員約300名）', '北海道的乳制品企业（员工约300人）', null, null,
   '北海道の大自然の中で、チーズ・バターなどの乳製品づくりを担当します。残業が少なく、生活費を抑えながら落ち着いて働ける環境です。', '在北海道的大自然中，负责奶酪、黄油等乳制品的生产。加班少，生活成本低，工作环境安稳。', ARRAY['製造機械のオペレーション', '原料の投入・充填', '品質チェック']::text[], ARRAY['生产设备操作', '原料投放·灌装', '质量检查']::text[]),
  (5, 'accommodation', 'published', true, 'kansai',
   '温泉旅館のフロント・接客スタッフ', '温泉旅馆 前台·接待员工', '京都府 京都市', '京都府 京都市',
   20, 26, 290, 370,
   ARRAY['dorm', 'chinese', 'highPay']::text[], ARRAY['social', 'meal', 'dorm', 'jpLesson', 'bonus', 'support2']::text[], true,
   'シフト制（早番7:00〜16:00／遅番13:00〜22:00）', '排班制（早班7:00〜16:00／晚班13:00〜22:00）', '週休2日・年間休日107日', '每周休2天·全年休107天', '月平均12時間程度', '月均约12小时',
   '寮あり（旅館まで徒歩5分・家賃1万円）', '有宿舍（步行5分钟到旅馆·月租1万日元）', '特定技能1号（宿泊）／日本語N3以上', '特定技能1号（酒店住宿）／日语N3以上', '賞与年2回（計2.5ヶ月分）', '奖金每年2次（共2.5个月工资）',
   '創業100年の老舗温泉旅館（客室50室・従業員約120名）', '拥有100年历史的老字号温泉旅馆（50间客房·员工约120人）', '中国人スタッフ6名在籍・中国語対応手当あり', '已有6名中国员工·有中文接待津贴',
   '京都の老舗温泉旅館で、中国からのお客様を中心とした接客・フロント業務を担当します。あなたの中国語がそのまま強みになり、手当にも反映されるお仕事です。', '在京都老字号温泉旅馆，主要负责接待中国客人和前台工作。您的中文能力就是最大的优势，还能获得相应津贴。', ARRAY['チェックイン・チェックアウト対応', '中国語圏のお客様の案内・通訳', '館内の接客サービス']::text[], ARRAY['办理入住·退房手续', '接待中文圈客人·翻译', '馆内接待服务']::text[]),
  (6, 'accommodation', 'published', false, 'kyushu_okinawa',
   'リゾートホテルのレストラン・客室スタッフ', '度假酒店 餐厅·客房员工', '沖縄県 那覇市', '冲绳县 那霸市',
   19, 24, 270, 330,
   ARRAY['dorm', 'chinese', 'noExp']::text[], ARRAY['social', 'meal', 'dorm', 'bonus']::text[], true,
   'シフト制・実働8時間', '排班制·实际工作8小时', '週休2日・年間休日110日', '每周休2天·全年休110天', '月平均8時間程度', '月均约8小时',
   '社員寮あり（家賃1.5万円）', '有员工宿舍（月租1.5万日元）', '特定技能1号（宿泊）／日本語N4以上', '特定技能1号（酒店住宿）／日语N4以上', '賞与年2回', '奖金每年2次',
   '沖縄県内で3施設を運営するリゾートホテルグループ（従業員約500名）', '在冲绳运营3家度假酒店的集团（员工约500人）', '中国人スタッフ12名在籍', '已有12名中国员工',
   '沖縄の人気リゾートホテルで、レストランサービスや客室業務を担当します。海外からのお客様が多く、語学力を活かして活躍できます。', '在冲绳人气度假酒店，负责餐厅服务和客房工作。外国客人多，可以充分发挥语言能力。', ARRAY['朝食・夕食レストランのサービス', '客室清掃の管理・チェック', 'お客様の案内対応']::text[], ARRAY['早餐·晚餐餐厅服务', '客房清扫管理·检查', '为客人提供向导服务']::text[]),
  (7, 'construction', 'published', false, 'kanto',
   '建設現場の型枠・鉄筋スタッフ', '建筑工地 模板·钢筋工', '神奈川県 横浜市', '神奈川县 横滨市',
   24, 30, 340, 430,
   ARRAY['dorm', 'highPay', 'support2', 'chinese']::text[], ARRAY['social', 'dorm', 'bonus', 'support2', 'jpLesson']::text[], true,
   '8:00〜17:00（実働8時間）', '8:00〜17:00（实际工作8小时）', '週休2日（土日）・年間休日110日', '每周休2天（周六日）·全年休110天', '月平均20時間程度（手当全額支給）', '月均约20小时（加班费全额支付）',
   '寮あり（個室・家賃無料）', '有宿舍（单人间·免房租）', '特定技能1号（建設）／日本語N4以上／経験1年以上歓迎', '特定技能1号（建筑）／日语N4以上／欢迎1年以上经验者', '賞与年2回・資格取得で手当あり', '奖金每年2次·取得资格证有津贴',
   '首都圏のマンション・商業施設を手がける建設会社（従業員約250名）', '承建首都圈公寓·商业设施的建筑公司（员工约250人）', '中国人スタッフ8名在籍', '已有8名中国员工',
   'マンションや商業施設の建設現場で、型枠・鉄筋工事を担当します。資格取得支援があり、特定技能2号への移行実績も多数。頑張った分だけ高収入を目指せます。', '在公寓和商业设施的建筑工地，负责模板和钢筋施工。公司支持考取资格证，有多名前辈成功转为特定技能2号。多劳多得，可以争取高收入。', ARRAY['型枠の組立・解体', '鉄筋の加工・組立', '現場の安全確認・整理整頓']::text[], ARRAY['模板的组装·拆除', '钢筋的加工·绑扎', '工地安全确认·整理整顿']::text[]),
  (8, 'manufacturing', 'published', true, 'chubu',
   '自動車部品の機械加工・検査スタッフ', '汽车零部件 机械加工·检验员工', '愛知県 岡崎市', '爱知县 冈崎市',
   23, 28, 330, 400,
   ARRAY['dorm', 'highPay', 'chinese', 'support2']::text[], ARRAY['social', 'dorm', 'bonus', 'flight', 'support2']::text[], true,
   '2交替制（8:00〜17:00／20:00〜翌5:00）', '两班倒（8:00〜17:00／20:00〜次日5:00）', '週休2日（土日）・年間休日121日', '每周休2天（周六日）·全年休121天', '月平均15時間程度（手当全額支給）', '月均约15小时（加班费全额支付）',
   '寮あり（1R・家賃1万円）', '有宿舍（单间·月租1万日元）', '特定技能1号（工業製品製造業）／日本語N4以上', '特定技能1号（工业产品制造业）／日语N4以上', '賞与年2回（計4ヶ月分）・昇給年1回', '奖金每年2次（共4个月工资）·每年加薪1次',
   '大手自動車メーカー系列の部品メーカー（従業員約1,500名）', '大型汽车厂商旗下的零部件企业（员工约1,500人）', '中国人スタッフ40名在籍・通訳スタッフ常駐', '已有40名中国员工·常驻翻译人员',
   '大手メーカー系列の工場で、自動車部品の機械オペレーションと検査を担当します。賞与4ヶ月分の手厚い待遇で、長く安定して働けます。', '在大型厂商旗下的工厂，负责汽车零部件的机械操作和检验。年奖金4个月工资的优厚待遇，工作长期稳定。', ARRAY['加工機械のオペレーション', '部品の寸法検査・外観検査', '設備の簡単なメンテナンス']::text[], ARRAY['加工设备操作', '零部件尺寸检验·外观检验', '设备的简单维护']::text[]),
  (9, 'shipbuilding', 'published', false, 'chugoku_shikoku',
   '造船所の溶接スタッフ', '造船厂 焊接工', '広島県 尾道市', '广岛县 尾道市',
   24, 29, 350, 420,
   ARRAY['dorm', 'highPay', 'support2']::text[], ARRAY['social', 'dorm', 'bonus', 'support2', 'meal']::text[], true,
   '8:00〜17:00（実働8時間）', '8:00〜17:00（实际工作8小时）', '週休2日・年間休日112日', '每周休2天·全年休112天', '月平均20時間程度', '月均约20小时',
   '寮あり（家賃5千円・社員食堂あり）', '有宿舍（月租5千日元·有员工食堂）', '特定技能1号（造船・舶用工業）／溶接経験1年以上／日本語N4以上', '特定技能1号（造船·船舶工业）／1年以上焊接经验／日语N4以上', '賞与年2回・技能手当あり', '奖金每年2次·有技能津贴',
   '瀬戸内海に面した中堅造船所（従業員約600名）', '面向濑户内海的中型造船厂（员工约600人）', '中国人スタッフ20名在籍', '已有20名中国员工',
   '大型船舶の建造現場で溶接を担当します。技能がそのまま給与に反映される評価制度があり、特定技能2号へ移行した先輩も多数活躍中です。', '在大型船舶的建造现场负责焊接工作。技能水平直接反映在工资上，已有多名前辈成功转为特定技能2号。', ARRAY['船体ブロックの溶接', '図面の確認・仮組み', '品質検査の補助']::text[], ARRAY['船体分段焊接', '图纸确认·预组装', '协助质量检验']::text[]),
  (10, 'automobile', 'published', false, 'chubu',
   '自動車整備士（ディーラー整備工場）', '汽车维修技师（4S店维修工厂）', '静岡県 浜松市', '静冈县 滨松市',
   21, 26, 300, 370,
   ARRAY['support2', 'lowOT']::text[], ARRAY['social', 'bonus', 'jpLesson', 'support2']::text[], false,
   '9:30〜18:30（実働8時間）', '9:30〜18:30（实际工作8小时）', '週休2日（火曜＋シフト）・年間休日105日', '每周休2天（周二＋排班）·全年休105天', '月平均15時間程度', '月均约15小时',
   '家賃補助あり（月2万円）', '有房租补贴（每月2万日元）', '特定技能1号（自動車整備）／整備経験または関連資格／日本語N4以上', '特定技能1号（汽车维修）／维修经验或相关资格证／日语N4以上', '賞与年2回・資格手当あり', '奖金每年2次·有资格证津贴',
   '国産車ディーラーの整備工場（従業員約150名）', '日系汽车4S店的维修工厂（员工约150人）', null, null,
   '正規ディーラーの整備工場で、点検・整備を担当します。最新設備と丁寧な研修があり、国家資格（自動車整備士）の取得もサポートします。', '在正规4S店的维修工厂，负责车辆检查和保养。设备先进、培训细致，还支持考取日本国家资格（汽车维修技师）。', ARRAY['定期点検・車検整備', 'エンジンオイル・タイヤ交換', '故障診断の補助']::text[], ARRAY['定期检查·车检保养', '更换机油·轮胎', '协助故障诊断']::text[]),
  (11, 'aviation', 'published', false, 'kanto',
   '空港グランドハンドリングスタッフ', '机场地勤员工（行李·货物）', '千葉県 成田市', '千叶县 成田市',
   20, 25, 290, 350,
   ARRAY['dorm', 'noExp', 'chinese']::text[], ARRAY['social', 'dorm', 'bonus', 'flight']::text[], true,
   'シフト制（早朝・日勤・夜勤）', '排班制（早班·白班·夜班）', '週休2日・年間休日115日', '每周休2天·全年休115天', '月平均10時間程度', '月均约10小时',
   '寮あり（家賃2万円・空港まで送迎あり）', '有宿舍（月租2万日元·有班车接送）', '特定技能1号（航空）／日本語N4以上／普通運転免許歓迎', '特定技能1号（航空）／日语N4以上／欢迎持有驾照者', '賞与年2回', '奖金每年2次',
   '国際空港で航空機の地上支援を行う会社（従業員約900名）', '在国际机场从事航空器地面保障的公司（员工约900人）', '中国人スタッフ10名在籍', '已有10名中国员工',
   '国際空港で、航空機の誘導や手荷物・貨物の搭載を担当します。世界とつながる空港で働ける、やりがいのあるお仕事です。', '在国际机场，负责航空器引导和行李·货物装卸。在连接世界的机场工作，很有成就感。', ARRAY['手荷物・貨物の仕分け・搭載', '航空機の誘導・けん引の補助', 'カート・車両の運転']::text[], ARRAY['行李·货物的分拣·装卸', '协助航空器引导·牵引', '驾驶行李车·作业车辆']::text[]),
  (12, 'agriculture', 'published', false, 'kanto',
   'トマト農園スタッフ（施設園芸）', '番茄农场员工（温室栽培）', '茨城県 つくば市', '茨城县 筑波市',
   18, 22, 250, 300,
   ARRAY['dorm', 'noExp', 'lowOT']::text[], ARRAY['social', 'dorm', 'meal']::text[], true,
   '8:00〜17:00（季節により変動あり）', '8:00〜17:00（随季节有变动）', '週休2日（シフト）・年間休日100日', '每周休2天（排班制）·全年休100天', '月平均5時間程度', '月均约5小时',
   '寮あり（一軒家シェア・家賃1万円）', '有宿舍（合租独栋·月租1万日元）', '特定技能1号（農業）／日本語N5以上', '特定技能1号（农业）／日语N5以上', '昇給あり・皆勤手当あり', '有加薪·有全勤奖',
   '最新設備のトマト農園を運営する農業法人（従業員約80名）', '运营现代化番茄农场的农业法人（员工约80人）', '中国人スタッフ5名在籍', '已有5名中国员工',
   '最新の温室でトマトの栽培・収穫を担当します。未経験でも丁寧に教えてもらえる、アットホームな職場です。', '在现代化温室负责番茄的栽培和采摘。没有经验也会有人耐心指导，工作氛围温馨。', ARRAY['収穫・選別・箱詰め', '苗の管理・水やり', '出荷準備']::text[], ARRAY['采摘·分拣·装箱', '苗木管理·浇水', '发货准备']::text[]),
  (13, 'fishery', 'published', false, 'kyushu_okinawa',
   '海上養殖スタッフ（ブリ・マグロ）', '海上养殖员工（鰤鱼·金枪鱼）', '長崎県 対馬市', '长崎县 对马市',
   19, 24, 280, 340,
   ARRAY['dorm', 'noExp']::text[], ARRAY['social', 'dorm', 'meal', 'bonus']::text[], false,
   '6:00〜15:00（季節変動あり）', '6:00〜15:00（随季节有变动）', '週休2日・年間休日105日', '每周休2天·全年休105天', '月平均8時間程度', '月均约8小时',
   '寮あり（家賃無料・食事付き）', '有宿舍（免房租·包餐）', '特定技能1号（漁業）／日本語N5以上／船酔いしにくい方', '特定技能1号（渔业）／日语N5以上／不易晕船者', '賞与年1回・水揚げ手当あり', '奖金每年1次·有渔获津贴',
   '対馬近海で養殖業を営む水産会社（従業員約60名）', '在对马近海从事养殖业的水产公司（员工约60人）', null, null,
   '美しい海でブリ・マグロの養殖を担当します。寮費・食費の負担がほとんどなく、しっかり貯金できる環境です。', '在美丽的大海上负责鰤鱼和金枪鱼的养殖。几乎不用负担房租和伙食费，很适合攒钱。', ARRAY['餌やり・生け簀（網）の管理', '魚の健康チェック', '水揚げ・出荷作業']::text[], ARRAY['投喂饲料·渔网管理', '鱼类健康检查', '捕捞·发货作业']::text[]),
  (14, 'building', 'published', false, 'kanto',
   'オフィスビルの清掃スタッフ', '写字楼保洁员工', '東京都 港区', '东京都 港区',
   19, 22, 260, 300,
   ARRAY['noExp', 'lowOT', 'chinese']::text[], ARRAY['social', 'bonus', 'jpLesson']::text[], true,
   '7:00〜16:00（実働8時間）', '7:00〜16:00（实际工作8小时）', '週休2日（土日中心）・年間休日120日', '每周休2天（以周六日为主）·全年休120天', 'ほぼなし（月5時間以下）', '基本没有（每月5小时以下）',
   '家賃補助あり（月1.5万円）', '有房租补贴（每月1.5万日元）', '特定技能1号（ビルクリーニング）／日本語N5以上', '特定技能1号（楼宇清洁）／日语N5以上', '賞与年2回・昇給年1回', '奖金每年2次·每年加薪1次',
   '都内のオフィスビルを管理する清掃会社（従業員約350名）', '管理东京市内写字楼的保洁公司（员工约350人）', '中国人スタッフ18名在籍', '已有18名中国员工',
   '都心のきれいなオフィスビルで、日常清掃を担当します。残業がほとんどなく、生活リズムを保ちやすいお仕事です。', '在市中心整洁的写字楼负责日常保洁。几乎不加班，容易保持规律的生活节奏。', ARRAY['共用部の清掃（床・トイレ等）', 'ゴミの回収・分別', '清掃用具の管理']::text[], ARRAY['公共区域保洁（地面·卫生间等）', '垃圾回收·分类', '保洁用具管理']::text[])
on conflict (id) do update set
  field_id = excluded.field_id, status = excluded.status, is_new = excluded.is_new, region = excluded.region, title_ja = excluded.title_ja, title_zh = excluded.title_zh, area_ja = excluded.area_ja, area_zh = excluded.area_zh, salary_min = excluded.salary_min, salary_max = excluded.salary_max, annual_min = excluded.annual_min, annual_max = excluded.annual_max, tags = excluded.tags, benefits = excluded.benefits, chinese_support = excluded.chinese_support, hours_ja = excluded.hours_ja, hours_zh = excluded.hours_zh, holidays_ja = excluded.holidays_ja, holidays_zh = excluded.holidays_zh, overtime_ja = excluded.overtime_ja, overtime_zh = excluded.overtime_zh, housing_ja = excluded.housing_ja, housing_zh = excluded.housing_zh, requirements_ja = excluded.requirements_ja, requirements_zh = excluded.requirements_zh, bonus_ja = excluded.bonus_ja, bonus_zh = excluded.bonus_zh, company_ja = excluded.company_ja, company_zh = excluded.company_zh, chinese_staff_ja = excluded.chinese_staff_ja, chinese_staff_zh = excluded.chinese_staff_zh, desc_ja = excluded.desc_ja, desc_zh = excluded.desc_zh, duties_ja = excluded.duties_ja, duties_zh = excluded.duties_zh;
select setval(pg_get_serial_sequence('jobs','id'), (select max(id) from jobs));
