-- ==========================================================
-- 樱聘 YingPin β版 データベース初期セットアップ（1ファイル版）
-- このファイルの内容をすべてコピーし、Supabaseの SQL Editor に
-- 貼り付けて「Run」を押してください。何度実行しても安全です。
-- 自動生成: 0001_schema.sql + 0002_seed.sql + 0003_security.sql + 0004_member_no.sql + 0005_consent.sql の結合（編集は各migrationsで）
-- ==========================================================

-- =========================================================
-- 樱聘 YingPin β版 データベーススキーマ（T-02）
-- テーブル定義＋RLS（行レベルセキュリティ）
-- Supabase の SQL Editor に貼り付けて実行する。
-- 冪等（何度実行しても安全）になるよう IF NOT EXISTS / OR REPLACE を使用。
-- =========================================================

-- ---------- 列挙型 ----------
do $$ begin
  create type gender_type as enum ('male', 'female', 'other');
exception when duplicate_object then null; end $$;

do $$ begin
  create type residence_type as enum ('jp', 'cn');
exception when duplicate_object then null; end $$;

do $$ begin
  create type job_status as enum ('draft', 'published', 'closed');
exception when duplicate_object then null; end $$;

do $$ begin
  -- 応募ステータス: 新規→連絡済→面接→内定→入社／辞退
  create type application_status as enum ('new', 'contacted', 'interview', 'offer', 'hired', 'declined');
exception when duplicate_object then null; end $$;

-- ---------- 更新時刻の自動更新 ----------
create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

-- ---------- staff_users（スタッフ／管理者） ----------
-- このテーブルに行がある auth ユーザーだけが管理画面にアクセスできる。
create table if not exists staff_users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  name text,
  created_at timestamptz not null default now()
);

-- スタッフ判定ヘルパー（RLSポリシーから参照）。
create or replace function is_staff()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from staff_users where id = auth.uid());
$$;

-- ---------- fields（特定技能2号移行対象の11分野・参照マスタ） ----------
create table if not exists fields (
  id text primary key,          -- 'restaurant' など（モックのFIELDS.idと一致）
  emoji text not null,
  color text not null,
  name_ja text not null,
  name_zh text not null,
  sort_order int not null default 0
);

-- ---------- members（会員／求職者） ----------
-- id = auth.users.id（本人だけが自分の行を読み書きできる）。
create table if not exists members (
  id uuid primary key references auth.users(id) on delete cascade,
  member_no text unique,             -- 表示用の会員番号 YP-YYYYMMDD-XXXX
  last_name text not null,
  first_name text not null,
  pinyin text not null,
  birth date,
  gender gender_type,
  nationality text not null default 'cn',
  residence residence_type not null default 'jp',
  address text,
  phone_code text not null default '+81',
  phone text not null,
  wechat_id text not null,
  email text,
  jlpt text,                         -- 'N1'〜'N5' / 'none'
  ssw_fields text[] not null default '{}',  -- 合格済み特定技能分野（fields.idの配列）
  other_qual text,
  verified boolean not null default false,  -- スタッフがWeChat本人確認後にON
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
drop trigger if exists trg_members_updated on members;
create trigger trg_members_updated before update on members
  for each row execute function set_updated_at();

-- ---------- jobs（求人。企業が特定されない情報のみ） ----------
create table if not exists jobs (
  id bigint generated by default as identity primary key,
  field_id text not null references fields(id),
  status job_status not null default 'draft',
  is_new boolean not null default false,
  region text not null,              -- 'kanto' など
  title_ja text not null, title_zh text not null,
  area_ja text not null,  area_zh text not null,
  salary_min int not null, salary_max int not null,   -- 月給（万円）
  annual_min int, annual_max int,                     -- 想定年収（万円）
  tags text[] not null default '{}',
  benefits text[] not null default '{}',
  chinese_support boolean not null default false,
  hours_ja text, hours_zh text,
  holidays_ja text, holidays_zh text,
  overtime_ja text, overtime_zh text,
  housing_ja text, housing_zh text,
  requirements_ja text, requirements_zh text,
  bonus_ja text, bonus_zh text,
  company_ja text, company_zh text,          -- 匿名の企業プロフィール（業種・規模のみ）
  chinese_staff_ja text, chinese_staff_zh text,
  desc_ja text, desc_zh text,
  duties_ja text[] not null default '{}',
  duties_zh text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
drop trigger if exists trg_jobs_updated on jobs;
create trigger trg_jobs_updated before update on jobs
  for each row execute function set_updated_at();
create index if not exists idx_jobs_status on jobs(status);
create index if not exists idx_jobs_field on jobs(field_id);
create index if not exists idx_jobs_region on jobs(region);

-- ---------- applications（応募） ----------
create table if not exists applications (
  id bigint generated by default as identity primary key,
  member_id uuid not null references members(id) on delete cascade,
  job_id bigint not null references jobs(id) on delete cascade,
  status application_status not null default 'new',
  staff_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (member_id, job_id)         -- 同じ求人への重複応募を防ぐ
);
drop trigger if exists trg_applications_updated on applications;
create trigger trg_applications_updated before update on applications
  for each row execute function set_updated_at();
create index if not exists idx_applications_member on applications(member_id);
create index if not exists idx_applications_job on applications(job_id);
create index if not exists idx_applications_status on applications(status);

-- ---------- favorites（お気に入り） ----------
create table if not exists favorites (
  member_id uuid not null references members(id) on delete cascade,
  job_id bigint not null references jobs(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (member_id, job_id)
);

-- =========================================================
-- RLS（行レベルセキュリティ）: 全テーブルで有効化
-- 原則: 会員は自分のデータのみ／求人閲覧はログイン必須／管理操作はスタッフのみ
-- =========================================================
alter table staff_users enable row level security;
alter table fields      enable row level security;
alter table members     enable row level security;
alter table jobs        enable row level security;
alter table applications enable row level security;
alter table favorites   enable row level security;

-- fields: 誰でも閲覧可（分野名は機密でない）。編集はスタッフのみ。
drop policy if exists fields_read on fields;
create policy fields_read on fields for select using (true);
drop policy if exists fields_staff_write on fields;
create policy fields_staff_write on fields for all using (is_staff()) with check (is_staff());

-- staff_users: スタッフ本人のみ自分の行を閲覧可（管理はダッシュボード/SQLで行う）。
drop policy if exists staff_self_read on staff_users;
create policy staff_self_read on staff_users for select using (id = auth.uid());

-- members: 本人は自分の行をCRUD。スタッフは全会員を閲覧・更新（本人確認フラグ等）。
drop policy if exists members_self_read on members;
create policy members_self_read on members for select using (id = auth.uid() or is_staff());
drop policy if exists members_self_insert on members;
create policy members_self_insert on members for insert with check (id = auth.uid());
drop policy if exists members_self_update on members;
create policy members_self_update on members for update
  using (id = auth.uid() or is_staff()) with check (id = auth.uid() or is_staff());

-- jobs: ログイン済みユーザーは公開中の求人のみ閲覧可。スタッフは全操作可。
drop policy if exists jobs_read_published on jobs;
create policy jobs_read_published on jobs for select
  using ((status = 'published' and auth.uid() is not null) or is_staff());
drop policy if exists jobs_staff_write on jobs;
create policy jobs_staff_write on jobs for all using (is_staff()) with check (is_staff());

-- applications: 本人は自分の応募をCRUD。スタッフは全応募を閲覧・更新。
drop policy if exists apps_self_read on applications;
create policy apps_self_read on applications for select using (member_id = auth.uid() or is_staff());
drop policy if exists apps_self_insert on applications;
create policy apps_self_insert on applications for insert with check (member_id = auth.uid());
drop policy if exists apps_staff_update on applications;
create policy apps_staff_update on applications for update using (is_staff()) with check (is_staff());

-- favorites: 本人のみ自分のお気に入りをCRUD。
drop policy if exists favs_self_all on favorites;
create policy favs_self_all on favorites for all
  using (member_id = auth.uid()) with check (member_id = auth.uid());

-- =========================================================
-- スタッフの登録方法（初回のみ・手動）
-- 1) 管理者本人がサイトから電話番号＋パスワードで会員登録またはログイン
-- 2) Supabase の Authentication → Users で自分の User UID をコピー
-- 3) 下のコメントを外し、UIDを貼って実行:
-- insert into staff_users (id, email, name)
--   values ('ここにUID', 'staff@example.com', '担当者名')
--   on conflict (id) do nothing;
-- =========================================================


-- =========================================================
-- 樱聘 YingPin シードデータ（T-02・自動生成）
-- 生成元: assets/js/data.js ／ 生成: app/supabase/_generate_seed.js
-- 特定技能2号移行対象の11分野＋サンプル求人14件（すべてダミー）。
-- 既存データを消してから入れ直すため、何度でも安全に再実行できる。
-- =========================================================

-- 分野マスタ（存在すれば更新）
insert into fields (id, emoji, color, name_ja, name_zh, sort_order) values
  ('building', '🧹', '#38BDF8', 'ビルクリーニング', '楼宇清洁', 0),
  ('manufacturing', '🏭', '#6366F1', '工業製品製造業', '工业产品制造业', 1),
  ('construction', '🏗️', '#F59E0B', '建設', '建筑', 2),
  ('shipbuilding', '🚢', '#0EA5E9', '造船・舶用工業', '造船·船舶工业', 3),
  ('automobile', '🔧', '#8B5CF6', '自動車整備', '汽车维修', 4),
  ('aviation', '✈️', '#06B6D4', '航空', '航空', 5),
  ('accommodation', '🏨', '#EC4899', '宿泊', '酒店住宿', 6),
  ('agriculture', '🌾', '#22C55E', '農業', '农业', 7),
  ('fishery', '🐟', '#3B82F6', '漁業', '渔业', 8),
  ('food_mfg', '🍱', '#F97316', '飲食料品製造業', '食品饮料制造', 9),
  ('restaurant', '🍜', '#EF4444', '外食業', '餐饮业', 10)
on conflict (id) do update set
  emoji = excluded.emoji, color = excluded.color,
  name_ja = excluded.name_ja, name_zh = excluded.name_zh, sort_order = excluded.sort_order;

-- サンプル求人（id一致なら上書き＝再実行しても応募データを消さない）
insert into jobs (
  id, field_id, status, is_new, region, title_ja, title_zh, area_ja, area_zh, salary_min, salary_max, annual_min, annual_max, tags, benefits, chinese_support, hours_ja, hours_zh, holidays_ja, holidays_zh, overtime_ja, overtime_zh, housing_ja, housing_zh, requirements_ja, requirements_zh, bonus_ja, bonus_zh, company_ja, company_zh, chinese_staff_ja, chinese_staff_zh, desc_ja, desc_zh, duties_ja, duties_zh
) values
  (1, 'restaurant', 'published', true, 'kanto',
   'ラーメンチェーンのキッチンスタッフ', '拉面连锁店 后厨员工', '東京都 新宿区', '东京都 新宿区',
   21, 25, 300, 360,
   ARRAY['dorm', 'chinese', 'noExp']::text[], ARRAY['social', 'meal', 'jpLesson', 'bonus', 'dorm', 'support2']::text[], true,
   'シフト制・実働8時間（10:00〜23:00の間）', '排班制·实际工作8小时（10:00〜23:00之间）', '週休2日制・年間休日110日', '每周休2天·全年休110天', '月平均10時間程度', '月均约10小时',
   '借上げ社宅あり（家賃の50%を会社負担）', '公司租赁宿舍（房租公司承担50%）', '特定技能1号（外食業）／日本語N4以上', '特定技能1号（餐饮业）／日语N4以上', '賞与年2回（計2ヶ月分）・昇給年1回', '奖金每年2次（共2个月工资）·每年加薪1次',
   '全国200店舗以上を展開する外食チェーン（従業員約1,200名）', '全国拥有200多家门店的连锁餐饮企业（员工约1,200人）', '中国人スタッフ15名在籍', '已有15名中国员工',
   '人気ラーメンチェーンの店舗キッチンで、仕込み・調理・盛り付けを担当します。マニュアルと研修が充実しており、日本での飲食経験がなくても安心してスタートできます。', '在人气拉面连锁店的后厨，负责备料、烹饪和摆盘。操作手册和培训体系完善，即使没有在日本餐饮业的经验也能安心上手。', ARRAY['仕込み・調理・盛り付け', '食材の発注・在庫管理の補助', 'キッチンの衛生管理']::text[], ARRAY['备料·烹饪·摆盘', '协助食材订购·库存管理', '后厨卫生管理']::text[]),
  (2, 'restaurant', 'published', false, 'kansai',
   '中華レストランのホール・キッチンスタッフ', '中餐厅 前厅·后厨员工', '大阪府 大阪市（難波）', '大阪府 大阪市（难波）',
   20, 24, 280, 340,
   ARRAY['dorm', 'chinese']::text[], ARRAY['social', 'meal', 'bonus', 'dorm']::text[], true,
   'シフト制・実働8時間（11:00〜23:00の間）', '排班制·实际工作8小时（11:00〜23:00之间）', '週休2日制（シフト）・年間休日105日', '每周休2天（排班制）·全年休105天', '月平均15時間程度', '月均约15小时',
   '寮あり（個室・家賃2万円）', '有宿舍（单人间·月租2万日元）', '特定技能1号（外食業）／日本語N4以上（ホールはN3歓迎）', '特定技能1号（餐饮业）／日语N4以上（前厅欢迎N3）', '賞与年1回・昇給あり', '奖金每年1次·有加薪',
   '関西で30店舗を展開する中華料理チェーン（従業員約400名）', '在关西拥有30家门店的中餐连锁企业（员工约400人）', '中国人スタッフ28名在籍・店長登用実績あり', '已有28名中国员工·有晋升店长的先例',
   '本格中華レストランでホールまたはキッチンを担当します。中国語がそのまま活かせる職場で、同郷の仲間も多く、日本が初めてでも働きやすい環境です。', '在正宗中餐厅担任前厅或后厨工作。可以直接发挥中文优势，同乡同事多，即使初到日本也能轻松适应。', ARRAY['ホール接客・オーダー対応', '調理・調理補助', '開店・閉店作業']::text[], ARRAY['前厅接待·点单服务', '烹饪·烹饪辅助', '开店·闭店作业']::text[]),
  (3, 'food_mfg', 'published', false, 'kanto',
   'お弁当・お惣菜工場の製造スタッフ', '便当·熟食工厂 生产员工', '埼玉県 川越市', '埼玉县 川越市',
   19, 23, 260, 320,
   ARRAY['dorm', 'noExp', 'lowOT', 'chinese']::text[], ARRAY['social', 'meal', 'dorm', 'jpLesson', 'bonus']::text[], true,
   '2交替制（6:00〜15:00／13:00〜22:00）', '两班倒（6:00〜15:00／13:00〜22:00）', '週休2日（工場カレンダー）・年間休日115日', '每周休2天（按工厂日历）·全年休115天', '月平均10時間程度', '月均约10小时',
   '寮あり（家具家電付き・家賃1.5万円）', '有宿舍（带家具家电·月租1.5万日元）', '特定技能1号（飲食料品製造業）／日本語N5以上', '特定技能1号（食品饮料制造）／日语N5以上', '賞与年2回・昇給年1回', '奖金每年2次·每年加薪1次',
   'コンビニ向け食品を製造する大手食品メーカーグループ（従業員約800名）', '为便利店生产食品的大型食品集团（员工约800人）', '中国人スタッフ35名在籍', '已有35名中国员工',
   '有名コンビニのお弁当・お惣菜を作る清潔な工場でのお仕事です。ライン作業が中心で、日本語がまだ少なくても始めやすく、先輩の中国人スタッフも多数活躍しています。', '在为知名便利店生产便当和熟食的洁净工厂工作。以流水线作业为主，日语基础不多也容易上手，有很多中国前辈员工。', ARRAY['食材の計量・盛り付け', '製造ラインでの調理補助', '検品・梱包']::text[], ARRAY['食材称量·摆盘', '流水线烹饪辅助', '检验·包装']::text[]),
  (4, 'food_mfg', 'published', true, 'hokkaido_tohoku',
   '乳製品工場の製造オペレーター', '乳制品工厂 生产操作员', '北海道 帯広市', '北海道 带广市',
   18, 22, 250, 310,
   ARRAY['dorm', 'lowOT', 'noExp']::text[], ARRAY['social', 'dorm', 'flight', 'bonus']::text[], false,
   '日勤中心（8:00〜17:00）', '以白班为主（8:00〜17:00）', '週休2日・年間休日120日', '每周休2天·全年休120天', '月平均5時間程度', '月均约5小时',
   '寮あり（家賃1万円・水道光熱費込み）', '有宿舍（月租1万日元·含水电费）', '特定技能1号（飲食料品製造業）／日本語N5以上', '特定技能1号（食品饮料制造）／日语N5以上', '賞与年2回', '奖金每年2次',
   '北海道の乳製品メーカー（従業員約300名）', '北海道的乳制品企业（员工约300人）', null, null,
   '北海道の大自然の中で、チーズ・バターなどの乳製品づくりを担当します。残業が少なく、生活費を抑えながら落ち着いて働ける環境です。', '在北海道的大自然中，负责奶酪、黄油等乳制品的生产。加班少，生活成本低，工作环境安稳。', ARRAY['製造機械のオペレーション', '原料の投入・充填', '品質チェック']::text[], ARRAY['生产设备操作', '原料投放·灌装', '质量检查']::text[]),
  (5, 'accommodation', 'published', true, 'kansai',
   '温泉旅館のフロント・接客スタッフ', '温泉旅馆 前台·接待员工', '京都府 京都市', '京都府 京都市',
   20, 26, 290, 370,
   ARRAY['dorm', 'chinese', 'highPay']::text[], ARRAY['social', 'meal', 'dorm', 'jpLesson', 'bonus', 'support2']::text[], true,
   'シフト制（早番7:00〜16:00／遅番13:00〜22:00）', '排班制（早班7:00〜16:00／晚班13:00〜22:00）', '週休2日・年間休日107日', '每周休2天·全年休107天', '月平均12時間程度', '月均约12小时',
   '寮あり（旅館まで徒歩5分・家賃1万円）', '有宿舍（步行5分钟到旅馆·月租1万日元）', '特定技能1号（宿泊）／日本語N3以上', '特定技能1号（酒店住宿）／日语N3以上', '賞与年2回（計2.5ヶ月分）', '奖金每年2次（共2.5个月工资）',
   '創業100年の老舗温泉旅館（客室50室・従業員約120名）', '拥有100年历史的老字号温泉旅馆（50间客房·员工约120人）', '中国人スタッフ6名在籍・中国語対応手当あり', '已有6名中国员工·有中文接待津贴',
   '京都の老舗温泉旅館で、中国からのお客様を中心とした接客・フロント業務を担当します。あなたの中国語がそのまま強みになり、手当にも反映されるお仕事です。', '在京都老字号温泉旅馆，主要负责接待中国客人和前台工作。您的中文能力就是最大的优势，还能获得相应津贴。', ARRAY['チェックイン・チェックアウト対応', '中国語圏のお客様の案内・通訳', '館内の接客サービス']::text[], ARRAY['办理入住·退房手续', '接待中文圈客人·翻译', '馆内接待服务']::text[]),
  (6, 'accommodation', 'published', false, 'kyushu_okinawa',
   'リゾートホテルのレストラン・客室スタッフ', '度假酒店 餐厅·客房员工', '沖縄県 那覇市', '冲绳县 那霸市',
   19, 24, 270, 330,
   ARRAY['dorm', 'chinese', 'noExp']::text[], ARRAY['social', 'meal', 'dorm', 'bonus']::text[], true,
   'シフト制・実働8時間', '排班制·实际工作8小时', '週休2日・年間休日110日', '每周休2天·全年休110天', '月平均8時間程度', '月均约8小时',
   '社員寮あり（家賃1.5万円）', '有员工宿舍（月租1.5万日元）', '特定技能1号（宿泊）／日本語N4以上', '特定技能1号（酒店住宿）／日语N4以上', '賞与年2回', '奖金每年2次',
   '沖縄県内で3施設を運営するリゾートホテルグループ（従業員約500名）', '在冲绳运营3家度假酒店的集团（员工约500人）', '中国人スタッフ12名在籍', '已有12名中国员工',
   '沖縄の人気リゾートホテルで、レストランサービスや客室業務を担当します。海外からのお客様が多く、語学力を活かして活躍できます。', '在冲绳人气度假酒店，负责餐厅服务和客房工作。外国客人多，可以充分发挥语言能力。', ARRAY['朝食・夕食レストランのサービス', '客室清掃の管理・チェック', 'お客様の案内対応']::text[], ARRAY['早餐·晚餐餐厅服务', '客房清扫管理·检查', '为客人提供向导服务']::text[]),
  (7, 'construction', 'published', false, 'kanto',
   '建設現場の型枠・鉄筋スタッフ', '建筑工地 模板·钢筋工', '神奈川県 横浜市', '神奈川县 横滨市',
   24, 30, 340, 430,
   ARRAY['dorm', 'highPay', 'support2', 'chinese']::text[], ARRAY['social', 'dorm', 'bonus', 'support2', 'jpLesson']::text[], true,
   '8:00〜17:00（実働8時間）', '8:00〜17:00（实际工作8小时）', '週休2日（土日）・年間休日110日', '每周休2天（周六日）·全年休110天', '月平均20時間程度（手当全額支給）', '月均约20小时（加班费全额支付）',
   '寮あり（個室・家賃無料）', '有宿舍（单人间·免房租）', '特定技能1号（建設）／日本語N4以上／経験1年以上歓迎', '特定技能1号（建筑）／日语N4以上／欢迎1年以上经验者', '賞与年2回・資格取得で手当あり', '奖金每年2次·取得资格证有津贴',
   '首都圏のマンション・商業施設を手がける建設会社（従業員約250名）', '承建首都圈公寓·商业设施的建筑公司（员工约250人）', '中国人スタッフ8名在籍', '已有8名中国员工',
   'マンションや商業施設の建設現場で、型枠・鉄筋工事を担当します。資格取得支援があり、特定技能2号への移行実績も多数。頑張った分だけ高収入を目指せます。', '在公寓和商业设施的建筑工地，负责模板和钢筋施工。公司支持考取资格证，有多名前辈成功转为特定技能2号。多劳多得，可以争取高收入。', ARRAY['型枠の組立・解体', '鉄筋の加工・組立', '現場の安全確認・整理整頓']::text[], ARRAY['模板的组装·拆除', '钢筋的加工·绑扎', '工地安全确认·整理整顿']::text[]),
  (8, 'manufacturing', 'published', true, 'chubu',
   '自動車部品の機械加工・検査スタッフ', '汽车零部件 机械加工·检验员工', '愛知県 岡崎市', '爱知县 冈崎市',
   23, 28, 330, 400,
   ARRAY['dorm', 'highPay', 'chinese', 'support2']::text[], ARRAY['social', 'dorm', 'bonus', 'flight', 'support2']::text[], true,
   '2交替制（8:00〜17:00／20:00〜翌5:00）', '两班倒（8:00〜17:00／20:00〜次日5:00）', '週休2日（土日）・年間休日121日', '每周休2天（周六日）·全年休121天', '月平均15時間程度（手当全額支給）', '月均约15小时（加班费全额支付）',
   '寮あり（1R・家賃1万円）', '有宿舍（单间·月租1万日元）', '特定技能1号（工業製品製造業）／日本語N4以上', '特定技能1号（工业产品制造业）／日语N4以上', '賞与年2回（計4ヶ月分）・昇給年1回', '奖金每年2次（共4个月工资）·每年加薪1次',
   '大手自動車メーカー系列の部品メーカー（従業員約1,500名）', '大型汽车厂商旗下的零部件企业（员工约1,500人）', '中国人スタッフ40名在籍・通訳スタッフ常駐', '已有40名中国员工·常驻翻译人员',
   '大手メーカー系列の工場で、自動車部品の機械オペレーションと検査を担当します。賞与4ヶ月分の手厚い待遇で、長く安定して働けます。', '在大型厂商旗下的工厂，负责汽车零部件的机械操作和检验。年奖金4个月工资的优厚待遇，工作长期稳定。', ARRAY['加工機械のオペレーション', '部品の寸法検査・外観検査', '設備の簡単なメンテナンス']::text[], ARRAY['加工设备操作', '零部件尺寸检验·外观检验', '设备的简单维护']::text[]),
  (9, 'shipbuilding', 'published', false, 'chugoku_shikoku',
   '造船所の溶接スタッフ', '造船厂 焊接工', '広島県 尾道市', '广岛县 尾道市',
   24, 29, 350, 420,
   ARRAY['dorm', 'highPay', 'support2']::text[], ARRAY['social', 'dorm', 'bonus', 'support2', 'meal']::text[], true,
   '8:00〜17:00（実働8時間）', '8:00〜17:00（实际工作8小时）', '週休2日・年間休日112日', '每周休2天·全年休112天', '月平均20時間程度', '月均约20小时',
   '寮あり（家賃5千円・社員食堂あり）', '有宿舍（月租5千日元·有员工食堂）', '特定技能1号（造船・舶用工業）／溶接経験1年以上／日本語N4以上', '特定技能1号（造船·船舶工业）／1年以上焊接经验／日语N4以上', '賞与年2回・技能手当あり', '奖金每年2次·有技能津贴',
   '瀬戸内海に面した中堅造船所（従業員約600名）', '面向濑户内海的中型造船厂（员工约600人）', '中国人スタッフ20名在籍', '已有20名中国员工',
   '大型船舶の建造現場で溶接を担当します。技能がそのまま給与に反映される評価制度があり、特定技能2号へ移行した先輩も多数活躍中です。', '在大型船舶的建造现场负责焊接工作。技能水平直接反映在工资上，已有多名前辈成功转为特定技能2号。', ARRAY['船体ブロックの溶接', '図面の確認・仮組み', '品質検査の補助']::text[], ARRAY['船体分段焊接', '图纸确认·预组装', '协助质量检验']::text[]),
  (10, 'automobile', 'published', false, 'chubu',
   '自動車整備士（ディーラー整備工場）', '汽车维修技师（4S店维修工厂）', '静岡県 浜松市', '静冈县 滨松市',
   21, 26, 300, 370,
   ARRAY['support2', 'lowOT']::text[], ARRAY['social', 'bonus', 'jpLesson', 'support2']::text[], false,
   '9:30〜18:30（実働8時間）', '9:30〜18:30（实际工作8小时）', '週休2日（火曜＋シフト）・年間休日105日', '每周休2天（周二＋排班）·全年休105天', '月平均15時間程度', '月均约15小时',
   '家賃補助あり（月2万円）', '有房租补贴（每月2万日元）', '特定技能1号（自動車整備）／整備経験または関連資格／日本語N4以上', '特定技能1号（汽车维修）／维修经验或相关资格证／日语N4以上', '賞与年2回・資格手当あり', '奖金每年2次·有资格证津贴',
   '国産車ディーラーの整備工場（従業員約150名）', '日系汽车4S店的维修工厂（员工约150人）', null, null,
   '正規ディーラーの整備工場で、点検・整備を担当します。最新設備と丁寧な研修があり、国家資格（自動車整備士）の取得もサポートします。', '在正规4S店的维修工厂，负责车辆检查和保养。设备先进、培训细致，还支持考取日本国家资格（汽车维修技师）。', ARRAY['定期点検・車検整備', 'エンジンオイル・タイヤ交換', '故障診断の補助']::text[], ARRAY['定期检查·车检保养', '更换机油·轮胎', '协助故障诊断']::text[]),
  (11, 'aviation', 'published', false, 'kanto',
   '空港グランドハンドリングスタッフ', '机场地勤员工（行李·货物）', '千葉県 成田市', '千叶县 成田市',
   20, 25, 290, 350,
   ARRAY['dorm', 'noExp', 'chinese']::text[], ARRAY['social', 'dorm', 'bonus', 'flight']::text[], true,
   'シフト制（早朝・日勤・夜勤）', '排班制（早班·白班·夜班）', '週休2日・年間休日115日', '每周休2天·全年休115天', '月平均10時間程度', '月均约10小时',
   '寮あり（家賃2万円・空港まで送迎あり）', '有宿舍（月租2万日元·有班车接送）', '特定技能1号（航空）／日本語N4以上／普通運転免許歓迎', '特定技能1号（航空）／日语N4以上／欢迎持有驾照者', '賞与年2回', '奖金每年2次',
   '国際空港で航空機の地上支援を行う会社（従業員約900名）', '在国际机场从事航空器地面保障的公司（员工约900人）', '中国人スタッフ10名在籍', '已有10名中国员工',
   '国際空港で、航空機の誘導や手荷物・貨物の搭載を担当します。世界とつながる空港で働ける、やりがいのあるお仕事です。', '在国际机场，负责航空器引导和行李·货物装卸。在连接世界的机场工作，很有成就感。', ARRAY['手荷物・貨物の仕分け・搭載', '航空機の誘導・けん引の補助', 'カート・車両の運転']::text[], ARRAY['行李·货物的分拣·装卸', '协助航空器引导·牵引', '驾驶行李车·作业车辆']::text[]),
  (12, 'agriculture', 'published', false, 'kanto',
   'トマト農園スタッフ（施設園芸）', '番茄农场员工（温室栽培）', '茨城県 つくば市', '茨城县 筑波市',
   18, 22, 250, 300,
   ARRAY['dorm', 'noExp', 'lowOT']::text[], ARRAY['social', 'dorm', 'meal']::text[], true,
   '8:00〜17:00（季節により変動あり）', '8:00〜17:00（随季节有变动）', '週休2日（シフト）・年間休日100日', '每周休2天（排班制）·全年休100天', '月平均5時間程度', '月均约5小时',
   '寮あり（一軒家シェア・家賃1万円）', '有宿舍（合租独栋·月租1万日元）', '特定技能1号（農業）／日本語N5以上', '特定技能1号（农业）／日语N5以上', '昇給あり・皆勤手当あり', '有加薪·有全勤奖',
   '最新設備のトマト農園を運営する農業法人（従業員約80名）', '运营现代化番茄农场的农业法人（员工约80人）', '中国人スタッフ5名在籍', '已有5名中国员工',
   '最新の温室でトマトの栽培・収穫を担当します。未経験でも丁寧に教えてもらえる、アットホームな職場です。', '在现代化温室负责番茄的栽培和采摘。没有经验也会有人耐心指导，工作氛围温馨。', ARRAY['収穫・選別・箱詰め', '苗の管理・水やり', '出荷準備']::text[], ARRAY['采摘·分拣·装箱', '苗木管理·浇水', '发货准备']::text[]),
  (13, 'fishery', 'published', false, 'kyushu_okinawa',
   '海上養殖スタッフ（ブリ・マグロ）', '海上养殖员工（鰤鱼·金枪鱼）', '長崎県 対馬市', '长崎县 对马市',
   19, 24, 280, 340,
   ARRAY['dorm', 'noExp']::text[], ARRAY['social', 'dorm', 'meal', 'bonus']::text[], false,
   '6:00〜15:00（季節変動あり）', '6:00〜15:00（随季节有变动）', '週休2日・年間休日105日', '每周休2天·全年休105天', '月平均8時間程度', '月均约8小时',
   '寮あり（家賃無料・食事付き）', '有宿舍（免房租·包餐）', '特定技能1号（漁業）／日本語N5以上／船酔いしにくい方', '特定技能1号（渔业）／日语N5以上／不易晕船者', '賞与年1回・水揚げ手当あり', '奖金每年1次·有渔获津贴',
   '対馬近海で養殖業を営む水産会社（従業員約60名）', '在对马近海从事养殖业的水产公司（员工约60人）', null, null,
   '美しい海でブリ・マグロの養殖を担当します。寮費・食費の負担がほとんどなく、しっかり貯金できる環境です。', '在美丽的大海上负责鰤鱼和金枪鱼的养殖。几乎不用负担房租和伙食费，很适合攒钱。', ARRAY['餌やり・生け簀（網）の管理', '魚の健康チェック', '水揚げ・出荷作業']::text[], ARRAY['投喂饲料·渔网管理', '鱼类健康检查', '捕捞·发货作业']::text[]),
  (14, 'building', 'published', false, 'kanto',
   'オフィスビルの清掃スタッフ', '写字楼保洁员工', '東京都 港区', '东京都 港区',
   19, 22, 260, 300,
   ARRAY['noExp', 'lowOT', 'chinese']::text[], ARRAY['social', 'bonus', 'jpLesson']::text[], true,
   '7:00〜16:00（実働8時間）', '7:00〜16:00（实际工作8小时）', '週休2日（土日中心）・年間休日120日', '每周休2天（以周六日为主）·全年休120天', 'ほぼなし（月5時間以下）', '基本没有（每月5小时以下）',
   '家賃補助あり（月1.5万円）', '有房租补贴（每月1.5万日元）', '特定技能1号（ビルクリーニング）／日本語N5以上', '特定技能1号（楼宇清洁）／日语N5以上', '賞与年2回・昇給年1回', '奖金每年2次·每年加薪1次',
   '都内のオフィスビルを管理する清掃会社（従業員約350名）', '管理东京市内写字楼的保洁公司（员工约350人）', '中国人スタッフ18名在籍', '已有18名中国员工',
   '都心のきれいなオフィスビルで、日常清掃を担当します。残業がほとんどなく、生活リズムを保ちやすいお仕事です。', '在市中心整洁的写字楼负责日常保洁。几乎不加班，容易保持规律的生活节奏。', ARRAY['共用部の清掃（床・トイレ等）', 'ゴミの回収・分別', '清掃用具の管理']::text[], ARRAY['公共区域保洁（地面·卫生间等）', '垃圾回收·分类', '保洁用具管理']::text[])
on conflict (id) do update set
  field_id = excluded.field_id, status = excluded.status, is_new = excluded.is_new, region = excluded.region, title_ja = excluded.title_ja, title_zh = excluded.title_zh, area_ja = excluded.area_ja, area_zh = excluded.area_zh, salary_min = excluded.salary_min, salary_max = excluded.salary_max, annual_min = excluded.annual_min, annual_max = excluded.annual_max, tags = excluded.tags, benefits = excluded.benefits, chinese_support = excluded.chinese_support, hours_ja = excluded.hours_ja, hours_zh = excluded.hours_zh, holidays_ja = excluded.holidays_ja, holidays_zh = excluded.holidays_zh, overtime_ja = excluded.overtime_ja, overtime_zh = excluded.overtime_zh, housing_ja = excluded.housing_ja, housing_zh = excluded.housing_zh, requirements_ja = excluded.requirements_ja, requirements_zh = excluded.requirements_zh, bonus_ja = excluded.bonus_ja, bonus_zh = excluded.bonus_zh, company_ja = excluded.company_ja, company_zh = excluded.company_zh, chinese_staff_ja = excluded.chinese_staff_ja, chinese_staff_zh = excluded.chinese_staff_zh, desc_ja = excluded.desc_ja, desc_zh = excluded.desc_zh, duties_ja = excluded.duties_ja, duties_zh = excluded.duties_zh;
select setval(pg_get_serial_sequence('jobs','id'), (select max(id) from jobs));


-- =========================================================
-- 樱聘 YingPin β版 公開前セキュリティ是正（PR-1a / T-15）
-- 対応Issue: #25 ①staff_note分離 / #26 ②verified・member_noロック / ③applications自己insert列固定
-- Supabase の SQL Editor に貼り付けて実行する。
-- 冪等（何度実行しても安全）。0001/0002 は改変せず、本ファイルで差分だけを当てる。
--
-- ⚠️ 実行順序: 先に新しいアプリ（本PR）をデプロイしてから、このSQLを実行すること。
--    （旧コードは applications.staff_note を読むため、SQLを先に流すと
--      デプロイ完了までの数分間、管理画面の応募一覧が表示できなくなる）
-- =========================================================


-- =========================================================
-- ① 応募のスタッフ内部メモを専用テーブルへ分離（Issue #25）
--
-- 問題: RLSは「行」単位でしか効かず、PostgREST（Supabase）は「列」を制限しない。
--       apps_self_read が自分の応募行を許可しているため、会員は自分のJWTで
--       select('staff_note') を直接実行でき、スタッフの内部メモを取得できた。
-- 対策: メモをスタッフ専用テーブルへ移し、applications から列ごと削除する。
--       （列単位のRLSは不可。view単独は所有者権限でRLSを迂回し得るため不採用）
-- =========================================================

create table if not exists application_staff_notes (
  application_id bigint primary key references applications(id) on delete cascade,
  note text,
  updated_at timestamptz not null default now()
);

comment on table application_staff_notes is
  'スタッフ内部メモ。会員に読まれないよう applications から分離（Issue #25）。RLSは is_staff() のみ。';

drop trigger if exists trg_app_staff_notes_updated on application_staff_notes;
create trigger trg_app_staff_notes_updated before update on application_staff_notes
  for each row execute function set_updated_at();

-- 既存メモの移送 → applications.staff_note を削除。
-- 列がまだ存在するときだけ動くので、再実行しても二重移送・エラーにならない。
do $$
begin
  if exists (
    select 1 from information_schema.columns
     where table_schema = 'public'
       and table_name   = 'applications'
       and column_name  = 'staff_note'
  ) then
    insert into application_staff_notes (application_id, note, updated_at)
    select id, staff_note, coalesce(updated_at, now())
      from applications
     where staff_note is not null
       and btrim(staff_note) <> ''
    on conflict (application_id) do nothing;

    alter table applications drop column staff_note;
    raise notice '① applications.staff_note を application_staff_notes へ移送し、列を削除しました。';
  else
    raise notice '① applications.staff_note は既に削除済みです（スキップ）。';
  end if;
end $$;

alter table application_staff_notes enable row level security;

-- スタッフだけが読み書きできる（会員は0行）。
drop policy if exists app_staff_notes_staff_all on application_staff_notes;
create policy app_staff_notes_staff_all on application_staff_notes
  for all using (is_staff()) with check (is_staff());

-- PostgREST 経由のアクセス権（実際に読めるかはRLSが決める）。anon には付与しない。
grant select, insert, update, delete on application_staff_notes to authenticated;


-- =========================================================
-- ② verified・member_no を会員が自己書換できないようにする（Issue #26）
--
-- 問題: members_self_update は id = auth.uid() を許可するだけで NEW/OLD を比較しない。
--       members_self_insert も CHECK が id = auth.uid() のみ。
--       → 会員が自分の verified（本人確認済フラグ）を true にできた。
--         SMSを使わない本サイトで verified は唯一の本人確認手段のため重大。
-- 対策: BEFORE INSERT/UPDATE トリガで防ぐ。
--       列権限 REVOKE UPDATE(verified) FROM authenticated は、会員もスタッフも
--       同じ authenticated ロールのためスタッフの toggleVerified まで止めてしまう＝不採用。
-- =========================================================

create or replace function members_guard_protected_columns()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- スタッフ（管理画面の toggleVerified 等）は従来どおり全項目を変更できる。
  if is_staff() then
    return new;
  end if;

  if tg_op = 'INSERT' then
    -- 登録時の自己 verified:true を禁止（本人確認はスタッフのWeChat確認のみ）。
    new.verified := false;
    return new;
  end if;

  -- UPDATE: 本人確認フラグと会員番号の自己書換を拒否する。
  if new.verified is distinct from old.verified then
    raise exception '本人確認フラグ(verified)はスタッフのみ変更できます'
      using errcode = '42501';
  end if;

  if new.member_no is distinct from old.member_no then
    raise exception '会員番号(member_no)は変更できません'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

comment on function members_guard_protected_columns() is
  'members の verified / member_no を非スタッフから保護する（Issue #26）。';

drop trigger if exists trg_members_guard on members;
create trigger trg_members_guard before insert or update on members
  for each row execute function members_guard_protected_columns();


-- =========================================================
-- ③ applications の自己insert列固定
--
-- 問題: apps_self_insert の CHECK は member_id = auth.uid() のみ。会員は応募作成時に
--       status を任意指定（例: 'hired'＝入社済）でき、id や created_at も詐称できた。
-- 対策: 非スタッフのINSERTはトリガで初期状態へ固定し、ポリシー側にも同条件を明示する。
-- =========================================================

create or replace function applications_guard_member_insert()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if is_staff() then
    return new;
  end if;

  -- 会員が作れるのは「自分の応募・初期状態(new)・現在時刻」だけ。
  new.status     := 'new'::application_status;
  new.created_at := now();
  new.updated_at := now();
  return new;
end;
$$;

comment on function applications_guard_member_insert() is
  '会員による応募作成を初期状態に固定する（PR-1a ③）。';

drop trigger if exists trg_applications_member_guard on applications;
create trigger trg_applications_member_guard before insert on applications
  for each row execute function applications_guard_member_insert();

-- 宣言的な二重防御（万一トリガが外れても初期状態以外の応募は入らない）。
drop policy if exists apps_self_insert on applications;
create policy apps_self_insert on applications for insert
  with check (member_id = auth.uid() and status = 'new');

-- id の自己指定を封じる（identity列を "by default" → "always" に変更）。
-- 応募を明示idで作るコードは存在しないため影響はない。
alter table applications alter column id set generated always;

-- ⚠️ 上の変更後は id を必ず自動採番するため、採番シーケンスが実データとずれていると
--    以後の応募がすべて主キー重複で失敗する。ここで現在の最大id+1へ揃えておく。
--    （過去に明示idでinsertされていた場合の保険。ズレていなければ何も変わらない）
select setval(
  pg_get_serial_sequence('applications', 'id'),
  coalesce((select max(id) from applications), 0) + 1,
  false
);


-- =========================================================
-- PostgREST（Supabase API）へスキーマ変更を反映
-- 通常は自動で反映されるが、新テーブルが「見つからない」場合の保険。
-- =========================================================
notify pgrst, 'reload schema';


-- =========================================================
-- 樱聘 YingPin β版 会員番号(member_no)のDB採番（PR-1b / T-15）
-- 対応Issue: #34 ⑩ member_no をDB側生成に移管
-- Supabase の SQL Editor に貼り付けて実行する。
-- 冪等（何度実行しても安全）。0001/0002/0003 は改変せず、本ファイルで差分だけを当てる。
--
-- ⚠️ 実行順序: このSQLを先に実行してから、新しいアプリ（本PR）をマージ＝デプロイすること。
--    （PR-1a の 0003 とは逆順。新コードは member_no を送らずDBの採番結果を読み戻すため、
--      SQLを当てる前に新コードが動くと会員番号が空のまま登録されてしまう。
--      逆に SQL を先に当てておけば、旧コードが送ってくる乱数の会員番号は
--      このトリガが黙って採番値へ置き換えるので、どの瞬間でもデータは壊れない）
--
-- 何が問題だったか:
--   会員番号は `client-auth.ts` の genMemberNo() が「YP-日付-4桁乱数」でブラウザ生成していた。
--   1日あたり9000通りしかないため、登録が増えると誕生日パラドックスで衝突する。
--   members.member_no には unique 制約があるので、衝突すると members.insert が失敗する。
--   ところが直前の supabase.auth.signUp() で作られた auth.users の行はそのまま残るため、
--   その電話番号は「登録済み」扱いで再登録できず、members に行が無いのでログインしても壊れる
--   ＝ その人は二度とサイトを使えなくなる（ロックアウト）。可用性の重大バグ。
-- どう直すか:
--   会員番号を「その日の連番」からDB側で組み立てる。連番はカウンタ表の行ロックで直列化されるので、
--   同時に何人登録しても同じ番号は絶対に出ない（＝構造的に衝突しない）。
-- =========================================================


-- =========================================================
-- ① 会員番号の採番カウンタ（日付ごとの連番）
--
-- 会員番号は「YP-<日付>-<その日の連番>」。日付ごとに1行を持ち、登録のたびに last_no を1増やす。
-- 同じ日の行を更新するため PostgreSQL の行ロックで自動的に直列化され、
-- 同時登録でも同じ連番が2人に渡ることはない。
-- =========================================================

create table if not exists member_no_counters (
  day_jst date primary key,          -- 日本時間の日付（会員番号に出る YYYYMMDD の部分）
  last_no integer not null           -- その日に最後に払い出した連番
);

comment on table member_no_counters is
  '会員番号(member_no)の日別採番カウンタ（Issue #34）。採番トリガ専用で、アプリからは読み書きしない。';

-- 会員・スタッフのどちらからも直接触らせない（採番はトリガ経由のみ）。
-- ポリシーを1つも作らない＝RLSにより誰も読めない。加えてテーブル権限自体も落とす。
-- 採番関数は security definer（所有者=postgres）で動くため、この制限の影響を受けない。
alter table member_no_counters enable row level security;
revoke all on member_no_counters from anon, authenticated;


-- =========================================================
-- ② 会員番号を1つ払い出す関数
--
-- 返り値の形式は従来と同じ「YP-YYYYMMDD-NNNN」（既存会員 YP-20260722-9443 等と同じ見た目）。
-- 連番は 1001 から始める。「YP-20260726-0001」だと1人目だと分かってしまうため、
-- 4桁の見た目を保ったまま、いかにも連番という印象にならない位置から始める。
--   ※ 1日8999人を超えると5桁になるが、番号が重複しないことは変わらない。
-- =========================================================

create or replace function generate_member_no(p_day date default null)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_day       date;
  v_seq       integer;
  v_candidate text;
  v_attempt   integer := 0;
begin
  -- 日付は日本時間で決める（DBのタイムゾーン設定＝Supabaseは既定UTC に左右されないよう明示）。
  v_day := coalesce(p_day, (now() at time zone 'Asia/Tokyo')::date);

  loop
    v_attempt := v_attempt + 1;

    -- その日の連番を1つ進めて受け取る。
    -- 同じ日の行を奪い合うので同時実行は自動的に1件ずつ処理され、同じ番号は出ない。
    insert into member_no_counters (day_jst, last_no)
    values (v_day, 1001)
    on conflict (day_jst) do update set last_no = member_no_counters.last_no + 1
    returning last_no into v_seq;

    -- lpad は桁があふれると切り捨ててしまうため、4桁を超える場合はそのまま連結する
    -- （切り捨てると番号が重複しうる）。
    v_candidate := 'YP-' || to_char(v_day, 'YYYYMMDD') || '-' ||
                   case when v_seq between 0 and 9999
                        then lpad(v_seq::text, 4, '0')
                        else v_seq::text
                   end;

    -- 移行前にブラウザが生成した乱数の番号と、たまたま同じになる可能性だけは残る。
    -- その場合はこの番号を捨てて次の連番へ進む（＝ unique 違反で登録が失敗しない）。
    exit when not exists (select 1 from members where member_no = v_candidate);

    if v_attempt >= 10000 then
      raise exception '会員番号の採番に失敗しました（% の空き番号が見つかりません）', v_day
        using errcode = '55000';
    end if;
  end loop;

  return v_candidate;
end;
$$;

comment on function generate_member_no(date) is
  '会員番号を日別連番で1つ払い出す（Issue #34）。members の採番トリガ専用。';

-- 一般利用者から直接呼べないようにする（呼べると連番だけを空回しできてしまう）。
revoke all on function generate_member_no(date) from public, anon, authenticated;


-- =========================================================
-- ③ 既存の会員ガード（0003・Issue #26）に採番を統合
--
-- 同じ members の BEFORE INSERT なので、トリガを増やさず既存関数に採番を足す。
-- 0003 で入れた保護（verified の自己ON禁止／verified・member_no の自己書換禁止）は
-- そのまま維持する。
-- =========================================================

create or replace function members_guard_protected_columns()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_is_staff boolean := is_staff();
begin
  if tg_op = 'INSERT' then
    if v_is_staff then
      -- スタッフ（管理画面・SQLからの登録）は従来どおり全項目を指定できる。
      -- 会員番号を省略したときだけDBが採番して埋める（空のまま残さない）。
      if new.member_no is null or btrim(new.member_no) = '' then
        new.member_no := generate_member_no();
      end if;
      return new;
    end if;

    -- 会員本人の新規登録:
    new.verified  := false;                -- 登録時の自己 verified:true を禁止（Issue #26）
    new.member_no := generate_member_no();  -- 会員番号はDBが採番。自己申告値は無視（Issue #34）
    return new;
  end if;

  -- UPDATE: スタッフ（管理画面の toggleVerified 等）は従来どおり全項目を変更できる。
  if v_is_staff then
    return new;
  end if;

  -- 本人確認フラグと会員番号の自己書換を拒否する（Issue #26）。
  if new.verified is distinct from old.verified then
    raise exception '本人確認フラグ(verified)はスタッフのみ変更できます'
      using errcode = '42501';
  end if;

  if new.member_no is distinct from old.member_no then
    raise exception '会員番号(member_no)は変更できません'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

comment on function members_guard_protected_columns() is
  'members の verified / member_no を非スタッフから保護し（Issue #26）、会員番号をDB採番する（Issue #34）。';

-- トリガ本体は 0003 と同じ（関数を差し替えただけ）。念のため貼り直して確実にする。
drop trigger if exists trg_members_guard on members;
create trigger trg_members_guard before insert or update on members
  for each row execute function members_guard_protected_columns();


-- =========================================================
-- ④ 会員番号が空の会員がいれば埋める（保険）
--
-- 通常は0件で何も起きない。実行順序を誤って「先にデプロイ→あとでSQL」をした場合、
-- その間に登録した人の会員番号が空になるため、このSQLをもう一度流せば復旧できる。
-- 番号はその人が登録した日（日本時間）で採番するので、後から埋めても日付が実態に合う。
--
-- ⚠️ 既に番号を持っている会員には一切触れない（既存の会員番号は変わらない）。
-- =========================================================

do $$
declare
  v_fixed integer := 0;
begin
  if exists (select 1 from members where member_no is null or btrim(member_no) = '') then
    -- 上のガードは「会員番号の変更」を拒否するため、埋める間だけトリガを外す。
    -- ※ セキュリティ上の穴にはならない: disable trigger は members に強いロックを取るため、
    --    このブロックが終わる（＝トリガが戻る）までサイトからの登録・更新は待たされる。
    --    つまり「ガードが外れている間に会員が verified を立てる」ような隙間は生じない。
    alter table members disable trigger trg_members_guard;

    update members m
       set member_no = generate_member_no((m.created_at at time zone 'Asia/Tokyo')::date)
     where m.member_no is null or btrim(m.member_no) = '';
    get diagnostics v_fixed = row_count;

    alter table members enable trigger trg_members_guard;
    raise notice '④ 会員番号が空だった % 件に番号を割り当てました。', v_fixed;
  else
    raise notice '④ 会員番号が空の会員はいません（スキップ）。';
  end if;
end $$;


-- =========================================================
-- 樱聘 YingPin β版 規約・プライバシーポリシーへの同意記録（D-2）
-- 対応: 弁護士確認論点リスト D-2 ／ 利用規約 第20条第2項 ／ プライバシーポリシー 第2条第3号
-- Supabase の SQL Editor に貼り付けて実行する。
-- 冪等（何度実行しても安全）。0001〜0004 は改変せず、本ファイルで差分だけを当てる。
--
-- ⚠️ 実行順序: このSQLを先に実行してから、新しいアプリ（本PR）をマージ＝デプロイすること。
--    先にデプロイすると、その間の登録で同意記録だけが残らない（登録自体は成功する）。
--
-- 何が問題だったか:
--   登録画面に「利用規約とプライバシーポリシーに同意する」チェックがあるが、
--   その値は RegisterWizard.tsx の画面状態として持っているだけで、サーバーへ送られず
--   保存もされていなかった。一方で規約 第20条第2項・PP 第2条第3号では
--   「同意の日時および同意の対象となった版数を記録する」と会員に約束している。
--   文書と実装が食い違っており、「同意していない」と言われたときに示す証拠が無い。
--
-- どう直すか:
--   同意を1件1行の追記専用テーブルに記録する。会員本人が後から書き換え・削除できない
--   ことが証拠として本質的なので、RLSとトリガの両方で封じる。
--
-- 設計上の判断:
--   ① 別テーブルにする。members に列を足すと members_self_update（本人が自分の行を
--      更新できるポリシー）の対象になり、本人が同意日時を書き換えられてしまう。
--   ② consent_type で種類を分けて持つ。現在は同意チェックが1つだけだが、論点A-9で
--      「越境移転の同意・第三者提供の同意を規約同意と分けるべきか」を確認中。
--      1回のチェックで複数種類の行を作る形にしておけば、後で画面を分割しても
--      スキーマは変えなくて済む。
--   ③ UPDATE / DELETE のポリシーを1つも作らない＝追記専用。スタッフも改変できない。
--      証拠は「後から誰も触れない」ことに価値があるため、意図的にそうしている。
--   ④ agreed_at と member_id はトリガがサーバー時刻・ログイン中のUIDで上書きする。
--      アプリは anon（公開鍵）で動き会員本人の権限で書き込むため、自己申告値を信用しない。
-- =========================================================


-- =========================================================
-- ① 同意記録テーブル
-- =========================================================

create table if not exists member_consents (
  id           bigint generated always as identity primary key,
  member_id    uuid        not null references members(id) on delete cascade,
  consent_type text        not null,   -- 何に対する同意か
  doc_version  text        not null,   -- 同意の対象となった版数（例 'v1.0'）
  agreed_at    timestamptz not null default now(),
  source       text        not null default 'register',  -- どの操作で得た同意か

  constraint member_consents_type_chk check (
    consent_type in ('terms', 'privacy', 'cross_border', 'third_party')
  ),
  -- 版数の書式を固定する（会員が任意の文字列を入れて記録を濁せないように）
  constraint member_consents_version_chk check (doc_version ~ '^v[0-9]+\.[0-9]+$'),
  constraint member_consents_source_chk check (
    source in ('register', 'reconsent', 'import')
  )
);

comment on table member_consents is
  '規約・プライバシーポリシー等への同意の記録（D-2）。追記専用。UPDATE/DELETEのポリシーを持たない。';
comment on column member_consents.consent_type is
  'terms=利用規約 / privacy=プライバシーポリシー / cross_border=越境移転 / third_party=第三者提供。'
  '現在は1つのチェックで terms・privacy・cross_border の3行を作る（論点A-9の回答次第で画面を分割できる）。';
comment on column member_consents.doc_version is
  '同意の対象となった文書の版数。アプリ側の定数 LEGAL_VERSION（src/lib/legal/version.ts）が正。';
comment on column member_consents.agreed_at is
  '同意日時。トリガがサーバー時刻で上書きするため、クライアントの申告値は反映されない。';

-- 「この会員の、この種類の、最新の同意」を引く用途に効く
create index if not exists idx_member_consents_lookup
  on member_consents (member_id, consent_type, agreed_at desc);


-- =========================================================
-- ② RLS: 本人は「自分の分を入れる」「自分の分を読む」だけ
--
-- UPDATE と DELETE のポリシーは意図的に作らない。
-- PostgreSQL の RLS は「ポリシーが無い操作は誰にもできない」ので、これで追記専用になる。
-- （テーブル権限側でも revoke して二重にする）
-- =========================================================

alter table member_consents enable row level security;

revoke update, delete on member_consents from anon, authenticated;

drop policy if exists member_consents_self_insert on member_consents;
create policy member_consents_self_insert on member_consents
  for insert with check (member_id = auth.uid());

drop policy if exists member_consents_self_read on member_consents;
create policy member_consents_self_read on member_consents
  for select using (member_id = auth.uid() or is_staff());


-- =========================================================
-- ③ 保護トリガ: 名義と日時をサーバー側で確定する
--
-- このアプリはサーバー側でも anon（公開鍵）で動き、members への insert も
-- 会員本人のセッションで行っている（auth.admin / service_role は使わない方針）。
-- したがって「クライアントが送ってきた値」は同意記録の証拠力を担保できない。
-- member_id と agreed_at はここで必ず上書きする。
--
-- スタッフ（is_staff()）は過去分の取り込み等があり得るため指定を許すが、
-- そもそも UPDATE / DELETE はできないので、入れ直しによる改竄はできない。
-- =========================================================

create or replace function member_consents_guard()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if is_staff() then
    return new;
  end if;

  new.member_id := auth.uid();   -- 他人名義での記録を防ぐ
  new.agreed_at := now();        -- 日時の自己申告を無効化（バックデート防止）
  new.source    := 'register';
  return new;
end;
$$;

comment on function member_consents_guard() is
  '同意記録の名義(member_id)と日時(agreed_at)をサーバー側で確定する（D-2）。非スタッフの自己申告値は捨てる。';

drop trigger if exists trg_member_consents_guard on member_consents;
create trigger trg_member_consents_guard before insert on member_consents
  for each row execute function member_consents_guard();


-- =========================================================
-- ④ 確認クエリ（実行後にこれを流して期待値どおりか見る）
--
--   select
--     (select count(*) from information_schema.tables
--        where table_schema='public' and table_name='member_consents')          as "① 表(期待値 1)",
--     (select count(*) from pg_policies
--        where schemaname='public' and tablename='member_consents')             as "② ポリシー(期待値 2)",
--     (select count(*) from pg_policies
--        where schemaname='public' and tablename='member_consents'
--          and cmd in ('UPDATE','DELETE'))                                      as "③ 改変ポリシー(期待値 0)",
--     (select count(*) from pg_trigger
--        where tgname='trg_member_consents_guard')                              as "④ 見張り役(期待値 1)";
--
--   → 1 / 2 / 0 / 1 になれば成功。
-- =========================================================


-- =========================================================
-- PostgREST（Supabase API）へスキーマ変更を反映
-- 通常は自動で反映されるが、新テーブルが「見つからない」場合の保険。
-- =========================================================
notify pgrst, 'reload schema';
