-- =========================================================
-- 樱聘 YingPin β版 データベーススキーマ（T-02）
-- テーブル定義＋RLS（行レベルセキュリティ）
-- Supabase の SQL Editor に貼り付けて実行する。
-- 冪等（何度実行しても安全）になるよう IF NOT EXISTS / OR REPLACE を使用。
-- =========================================================

-- ---------- 列挙型 ----------
do $$ begin
  create type gender_type as enum ('male', 'female', 'other');
exception when duplicate_object then null; end $$;

do $$ begin
  create type residence_type as enum ('jp', 'cn');
exception when duplicate_object then null; end $$;

do $$ begin
  create type job_status as enum ('draft', 'published', 'closed');
exception when duplicate_object then null; end $$;

do $$ begin
  -- 応募ステータス: 新規→連絡済→面接→内定→入社／辞退
  create type application_status as enum ('new', 'contacted', 'interview', 'offer', 'hired', 'declined');
exception when duplicate_object then null; end $$;

-- ---------- 更新時刻の自動更新 ----------
create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

-- ---------- staff_users（スタッフ／管理者） ----------
-- このテーブルに行がある auth ユーザーだけが管理画面にアクセスできる。
create table if not exists staff_users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  name text,
  created_at timestamptz not null default now()
);

-- スタッフ判定ヘルパー（RLSポリシーから参照）。
create or replace function is_staff()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from staff_users where id = auth.uid());
$$;

-- ---------- fields（特定技能2号移行対象の11分野・参照マスタ） ----------
create table if not exists fields (
  id text primary key,          -- 'restaurant' など（モックのFIELDS.idと一致）
  emoji text not null,
  color text not null,
  name_ja text not null,
  name_zh text not null,
  sort_order int not null default 0
);

-- ---------- members（会員／求職者） ----------
-- id = auth.users.id（本人だけが自分の行を読み書きできる）。
create table if not exists members (
  id uuid primary key references auth.users(id) on delete cascade,
  member_no text unique,             -- 表示用の会員番号 YP-YYYYMMDD-XXXX
  last_name text not null,
  first_name text not null,
  pinyin text not null,
  birth date,
  gender gender_type,
  nationality text not null default 'cn',
  residence residence_type not null default 'jp',
  address text,
  phone_code text not null default '+81',
  phone text not null,
  wechat_id text not null,
  email text,
  jlpt text,                         -- 'N1'〜'N5' / 'none'
  ssw_fields text[] not null default '{}',  -- 合格済み特定技能分野（fields.idの配列）
  other_qual text,
  verified boolean not null default false,  -- スタッフがWeChat本人確認後にON
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
drop trigger if exists trg_members_updated on members;
create trigger trg_members_updated before update on members
  for each row execute function set_updated_at();

-- ---------- jobs（求人。企業が特定されない情報のみ） ----------
create table if not exists jobs (
  id bigint generated by default as identity primary key,
  field_id text not null references fields(id),
  status job_status not null default 'draft',
  is_new boolean not null default false,
  region text not null,              -- 'kanto' など
  title_ja text not null, title_zh text not null,
  area_ja text not null,  area_zh text not null,
  salary_min int not null, salary_max int not null,   -- 月給（万円）
  annual_min int, annual_max int,                     -- 想定年収（万円）
  tags text[] not null default '{}',
  benefits text[] not null default '{}',
  chinese_support boolean not null default false,
  hours_ja text, hours_zh text,
  holidays_ja text, holidays_zh text,
  overtime_ja text, overtime_zh text,
  housing_ja text, housing_zh text,
  requirements_ja text, requirements_zh text,
  bonus_ja text, bonus_zh text,
  company_ja text, company_zh text,          -- 匿名の企業プロフィール（業種・規模のみ）
  chinese_staff_ja text, chinese_staff_zh text,
  desc_ja text, desc_zh text,
  duties_ja text[] not null default '{}',
  duties_zh text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
drop trigger if exists trg_jobs_updated on jobs;
create trigger trg_jobs_updated before update on jobs
  for each row execute function set_updated_at();
create index if not exists idx_jobs_status on jobs(status);
create index if not exists idx_jobs_field on jobs(field_id);
create index if not exists idx_jobs_region on jobs(region);

-- ---------- applications（応募） ----------
create table if not exists applications (
  id bigint generated by default as identity primary key,
  member_id uuid not null references members(id) on delete cascade,
  job_id bigint not null references jobs(id) on delete cascade,
  status application_status not null default 'new',
  staff_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (member_id, job_id)         -- 同じ求人への重複応募を防ぐ
);
drop trigger if exists trg_applications_updated on applications;
create trigger trg_applications_updated before update on applications
  for each row execute function set_updated_at();
create index if not exists idx_applications_member on applications(member_id);
create index if not exists idx_applications_job on applications(job_id);
create index if not exists idx_applications_status on applications(status);

-- ---------- favorites（お気に入り） ----------
create table if not exists favorites (
  member_id uuid not null references members(id) on delete cascade,
  job_id bigint not null references jobs(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (member_id, job_id)
);

-- =========================================================
-- RLS（行レベルセキュリティ）: 全テーブルで有効化
-- 原則: 会員は自分のデータのみ／求人閲覧はログイン必須／管理操作はスタッフのみ
-- =========================================================
alter table staff_users enable row level security;
alter table fields      enable row level security;
alter table members     enable row level security;
alter table jobs        enable row level security;
alter table applications enable row level security;
alter table favorites   enable row level security;

-- fields: 誰でも閲覧可（分野名は機密でない）。編集はスタッフのみ。
drop policy if exists fields_read on fields;
create policy fields_read on fields for select using (true);
drop policy if exists fields_staff_write on fields;
create policy fields_staff_write on fields for all using (is_staff()) with check (is_staff());

-- staff_users: スタッフ本人のみ自分の行を閲覧可（管理はダッシュボード/SQLで行う）。
drop policy if exists staff_self_read on staff_users;
create policy staff_self_read on staff_users for select using (id = auth.uid());

-- members: 本人は自分の行をCRUD。スタッフは全会員を閲覧・更新（本人確認フラグ等）。
drop policy if exists members_self_read on members;
create policy members_self_read on members for select using (id = auth.uid() or is_staff());
drop policy if exists members_self_insert on members;
create policy members_self_insert on members for insert with check (id = auth.uid());
drop policy if exists members_self_update on members;
create policy members_self_update on members for update
  using (id = auth.uid() or is_staff()) with check (id = auth.uid() or is_staff());

-- jobs: ログイン済みユーザーは公開中の求人のみ閲覧可。スタッフは全操作可。
drop policy if exists jobs_read_published on jobs;
create policy jobs_read_published on jobs for select
  using ((status = 'published' and auth.uid() is not null) or is_staff());
drop policy if exists jobs_staff_write on jobs;
create policy jobs_staff_write on jobs for all using (is_staff()) with check (is_staff());

-- applications: 本人は自分の応募をCRUD。スタッフは全応募を閲覧・更新。
drop policy if exists apps_self_read on applications;
create policy apps_self_read on applications for select using (member_id = auth.uid() or is_staff());
drop policy if exists apps_self_insert on applications;
create policy apps_self_insert on applications for insert with check (member_id = auth.uid());
drop policy if exists apps_staff_update on applications;
create policy apps_staff_update on applications for update using (is_staff()) with check (is_staff());

-- favorites: 本人のみ自分のお気に入りをCRUD。
drop policy if exists favs_self_all on favorites;
create policy favs_self_all on favorites for all
  using (member_id = auth.uid()) with check (member_id = auth.uid());

-- =========================================================
-- スタッフの登録方法（初回のみ・手動）
-- 1) 管理者本人がサイトから電話番号＋パスワードで会員登録またはログイン
-- 2) Supabase の Authentication → Users で自分の User UID をコピー
-- 3) 下のコメントを外し、UIDを貼って実行:
-- insert into staff_users (id, email, name)
--   values ('ここにUID', 'staff@example.com', '担当者名')
--   on conflict (id) do nothing;
-- =========================================================
